### ISSUE TITLE
Error: There is an unnecessary space between tag name and backward slash '</ ..'.

### ISSUE THREAD

**Issue by BognarB** [NaturalIntelligence/fast-xml-parser#300] opened 2020-11-05 22:58 UTC
### Checklist

* [x] Have you asked your question on Stackoverflow or similar forum? >>> Topic not found.
* [X] Are you running the latest version?
* [X] Have you included sample input, output, error, and expected output? >>> Partial
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input
sorry, i can't publish, but it worked at online [tool](https://naturalintelligence.github.io/fast-xml-parser/)
it is a fiscal document under gov/law protection.

### Code
glob( "./danfes/**/*.xml", function( err, files ) {
	if (err) throw err;
	files.forEach((element) => {
		const xmlData = xml.readFileSync(element, { encoding: "utf-8" });
		const jsonData = parser.parse(
			xmlData, {
				attrNodeName: "#attr",
				textNodeName: "#text",
				attributeNamePrefix: "",
				arrayMode: false,
				ignoreAttributes: false,
				parseAttributeValue: true,
			}, true);
		console.log("element",element,"jsonData", jsonData);
	});
});

### Output
element ./danfes/NF ENTRADA/2015/02.2015/Cota/Advanced NF 3027408-nfe.xml jsonData {
  nfeProc: {
    '#attr': { versao: 3.1, xmlns: 'http://www.portalfiscal.inf.br/nfe' },
    NFe: { '#attr': [Object], infNFe: [Object], Signature: [Object] },
    protNFe: { '#attr': [Object], infProt: [Object] }
  }
}
/Users/renatobognar/eclipse-workspace/le_xml_nota_danfe_entrada/trunk/node_modules/fast-xml-parser/src/parser.js:15
      throw Error( result.err.msg)
      ^

Error: There is an unnecessary space between tag name and backward slash '</ ..'.
    at Object.exports.parse (/Users/renatobognar/eclipse-workspace/le_xml_nota_danfe_entrada/trunk/node_modules/fast-xml-parser/src/parser.js:15:13)
    at /Users/renatobognar/eclipse-workspace/le_xml_nota_danfe_entrada/trunk/index.js:23:27
    at Array.forEach (<anonymous>)
    at /Users/renatobognar/eclipse-workspace/le_xml_nota_danfe_entrada/trunk/index.js:21:8
    at f (/Users/renatobognar/eclipse-workspace/le_xml_nota_danfe_entrada/trunk/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/renatobognar/eclipse-workspace/le_xml_nota_danfe_entrada/trunk/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:314:20)
    at Glob._finish (/Users/renatobognar/eclipse-workspace/le_xml_nota_danfe_entrada/trunk/node_modules/glob/glob.js:197:8)
    at done (/Users/renatobognar/eclipse-workspace/le_xml_nota_danfe_entrada/trunk/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/Users/renatobognar/eclipse-workspace/le_xml_nota_danfe_entrada/trunk/node_modules/glob/glob.js:637:12)

**Would you like to work on this issue?**

- [X] Yes
- [ ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment] 2020-11-06 02:20
It looks like the issue is with input XML only. You can open the XML in some text editor and do regular expression search for `<\s+/` pattern. If you find any, you know where to fix it.

**Comment by BognarB** [comment] 2020-11-06 12:40
Hello my friend

Thanks for answering.

I found it.

This is the piece of xml code as is on the file:

 

 

<xMun>TABOÃO DA

SERRA</xMun><UF>SP</UF><CEP>06790240</CEP><cPais>1058</cPais><xPais>Brasil</

xPais><fone>1147017387</fone></enderDest><IE>675146522119</IE></dest><det

nItem="1"><prod><cProd>1780416</cProd><cEAN/><xProd>BETONEIRA 150LTS MB 150L

220V

152469</xProd><NCM>84743100</NCM><CFOP>5102</CFOP><uCom>PC</uCom><qCom>1.00<

/qCom><vUnCom>1199.00</vUnCom><vProd>1199.00</vProd><cEANTrib/><uTrib>PC</uT

rib><qTrib>1.00</qTrib><vUnTrib>1199.00</vUnTrib><indTot>1</indTot></prod><i

mposto><ICMS><ICMS20><orig>0</orig><CST>20</CST><modBC>2</modBC><pRedBC>26.6

6</pRedBC><vBC>879.35</vBC><pICMS>12.00</pICMS><vICMS>105.51</vICMS></ICMS20

></ICMS><PIS><PISAliq><CST>01</CST><vBC>1199.00</vBC><pPIS>1.65</pPIS><vPIS>

19.78</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>1199.00</v

 

 

 

 

 

AVISO LEGAL ..Esta mensagem é destinada exclusivamente para a(s) pessoa(s) a quem é dirigida, podendo conter informação confidencial e/ou legalmente privilegiada. Se você não for destinatário desta mensagem, desde já fica notificado de abster-se a divulgar, copiar, distribuir, examinar ou, de qualquer forma, utilizar a informação contida nesta mensagem, por ser ilegal. Caso você tenha recebido esta mensagem por engano, pedimos que nos retorne este E-Mail, promovendo, desde logo, a eliminação do seu conteúdo em sua base de dados, registros ou sistema de controle. Fica desprovida de eficácia e validade a mensagem que contiver vínculos obrigacionais, expedida por quem não detenha poderes de representação. 

LEGAL ADVICE...This message is exclusively destined for the people to whom it is directed, and it can bear private and/or legally exceptional information. If you are not addressee of this message, since now you are advised to not release, copy, distribute, check or, otherwise, use the information contained in this message, because it is illegal. If you received this message by mistake, we ask you to return this email, making possible, as soon as possible, the elimination of its contents of your database, registrations or controls system. The message that bears any mandatory links, issued by someone who has no representation powers, shall be null or void.

 

De: Amit K Gupta <notifications@github.com>
Responder para: NaturalIntelligence/fast-xml-parser <reply@reply.github.com>
Data: quinta-feira, 5 de novembro de 2020 23:20
Para: NaturalIntelligence/fast-xml-parser <fast-xml-parser@noreply.github.com>
Cc: ""renatobognar@gmail.com" renatobognar@gmail.com" <renatobognar@gmail.com>, Author <author@noreply.github.com>
Assunto: Re: [NaturalIntelligence/fast-xml-parser] Error: There is an unnecessary space between tag name and backward slash '</ ..'. (#300)

 

It looks like the issue is with input XML only. You can open the XML in some text editor and do regular expression search for <\s+/ pattern. If you find any, you know where to fix it.

**Comment by amitguptagwl** [comment] 2020-11-15 02:03
I'm closing this issue then.

**Closed by amitguptagwl** 2020-11-15 02:03 UTC
