### ISSUE TITLE
Inline tag missed order and position

### ISSUE THREAD

**Issue by Kraigo** [NaturalIntelligence/fast-xml-parser#175] opened 2019-07-24 11:11 UTC
### Checklist

* [ ] Have you asked your question on Stackoverflow or similar forum?
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [ ] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input

Issue is inline tag in text will missed position and trim all spaces

### Code
```js
const xml = require('fast-xml-parser');

const data = '<p>Test string <emphasis> test</emphasis> second part of test string</p>'

const options = {
    ignoreAttributes: false
}

const result = xml.parse(data, options);
```

### Output

```json
{
  "p": {
    "#text": "Test stringsecond part of test string",
    "emphasis": "test"
  }
}
```

### expected data

But it should keep "Array order" 
```json
{
  "p": [
    "Test string",
    { "emphasis": "test" },
    "second part of test string"
  ]
}
```
**Would you like to work on this issue?**

- [ ] Yes
- [x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment] 2019-07-27 07:56
This is not a bug but expected behavior. However, if you need to maintain the order as per your example, we can provide some property to do that.

**Comment by amitguptagwl** [comment] 2019-10-02 06:39
One of the suggested solution can be;
```js
{
  "p": {
    "#text": ["Test string", "second part of test string"],
    "emphasis": "test"
  }
}
```
let me know your views

**Comment by lazarljubenovic** [comment] 2019-10-28 10:25
I don't think the example you've given would work. You still don't know which items come in which order. Something like the first idea would work.

I don't think this is expected behavior for most users. Maybe some _don't mind_ that the order is not preserved and that all `#text` nodes are merged into one, but I don't see how it's "expected" that all these XML files give the exactly same output in the resulting structure:

```xml
<a>left  right<b>middle</b></a>

<a><b>middle</b>left  right</a>

<a>left <b>middle</b> right</a>

<a>le<b>middle</b>ft  right</a>
```

I was almost certain that this was my misunderstanding of the library that [I opened a question on SO](https://stackoverflow.com/questions/58589063/get-text-nodes-separately-in-the-correct-order-with-fast-xml-parser) before even checking for issues here.

**Comment by amitguptagwl** [comment] 2019-10-29 02:18
Let me check it in arrayMode.

**Comment by amitguptagwl** [comment] 2019-11-01 02:15
I have created a separate issue to discuss this requirement #197

**Comment by amitguptagwl** [comment] 2021-11-17 03:25
check `preserveOrder` option with FXPv4 and let us know if it fulfill your purpose. Create a new issue if it doesn't

**Closed by amitguptagwl** 2021-11-17 03:25 UTC
