### ISSUE TITLE
multiple elements with white space is "valid" but errors out

### ISSUE THREAD

**Issue by bryanSME** [NaturalIntelligence/fast-xml-parser#266] opened 2020-05-29 00:55 UTC
* [x] Are you running the latest version?
* [x] Have you included sample input, output, error, and expected output? 
* [x] Have you checked if you are using correct configuration?
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
The following example data passes validation but fails to parse.

### Input

- **FAIL** -- `TypeError: Cannot read property 'parent' of undefined`
![image](https://user-images.githubusercontent.com/16226280/83195733-b19eb500-a108-11ea-9091-3d255ae0c121.png)

- **PASS**
![image](https://user-images.githubusercontent.com/16226280/83195657-92078c80-a108-11ea-9ff6-a363f75ebc3d.png)

- **PASS**
![image](https://user-images.githubusercontent.com/16226280/83196193-7650b600-a109-11ea-83d9-8e5aba15d055.png)

### Code
```
import parser from 'fast-xml-parser';
import fse from 'fs-extra';
...
const buff = fse.readFile(filename)).toString();
if (parser.validate(buff, options) === true) {
    jsonObj = parser.parse(xmlData);
}
```

### Output
```
TypeError: Cannot read property 'parent' of undefined

      44 |   };
      45 |   if (parser.validate(xmlData, options) === true) {
    > 46 |     jsonObj = parser.parse(xmlData);
         |                      ^
      47 |   }
      48 |   return jsonObj;
      49 | }

      at Object.getTraversalObj (node_modules/fast-xml-parser/src/xmlstr2xmlnode.js:208:35)
      at Object.parse (node_modules/fast-xml-parser/src/parser.js:19:39)
      at convertToJSON (api/ModelIO/ModelLoadAtStartup.ts:46:22)
      at _callee5$ (api/ModelIO/ModelLoadAtStartup.test.ts:95:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:135:20)
      at node_modules/regenerator-runtime/runtime.js:145:13
```

### expected data
**no error**

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

**Comment by amitguptagwl** [comment] 2020-05-29 01:24
Duplicate of #252 

Issue has been fixed and available on Github. It'll be publichsed on npm tomorrow.

**Closed by amitguptagwl** 2020-05-29 01:24 UTC
