### ISSUE TITLE
cannot read property 'addChild' after upgrade to 3.17.1

### ISSUE THREAD

**Issue by jdmairs** [NaturalIntelligence/fast-xml-parser#252] opened 2020-05-19 15:02 UTC
* [x ] Are you running the latest version? yes: 3.17.1
* [x ] Have you included sample input, output, error, and expected output? yes
* [ x] Have you checked if you are using correct configuration? yes
* [ x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)? yes

### Description
After updating from 3.16.0 to 3.17.1 our Jest test case against a sample xml file fails.

### Input
This failure is also reproduced on the online tool.

It validates ok but does not produce output.

The file Mondial-3.0.xml from the following website:
http://aiweb.cs.washington.edu/research/projects/xmltk/xmldata/www/repository.html#pir

### Output

<img width="847" alt="image" src="https://user-images.githubusercontent.com/5624808/82342455-a38dbd80-99bf-11ea-9204-53acfcd27fb8.png">

### expected data

**Would you like to work on this issue?**

- [ ] Yes
- [x ] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment] 2020-05-20 01:10
Thanks for informing me. Let me check the issue.

**Comment by amitguptagwl** [comment] 2020-05-20 01:19
This XML is working fine for me. Can you please check if there is any other xml you tried with?

**Comment by jdmairs** [comment] 2020-05-26 21:07
Puzzling...I'm using this online tool: https://naturalintelligence.github.io/fast-xml-parser/

It just sits here doing nothing for me:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/5624808/82950381-3952bb00-9f73-11ea-998d-2977d31863d9.png">

**Comment by jdmairs** [comment] 2020-05-26 21:11
I just deleted my package-lock.json and node_modules folder for a different reason all together and now I'm seeing the same crash with 3.16.0.

I'm guessing this is a dependency issue on my side.  Something's conflicting.

**Comment by amitguptagwl** [comment] 2020-05-27 03:08
I'm not sure about online tool as the string is so large if it fails but we can debug that as well if it is confirmed.

**Comment by amitguptagwl** [comment] 2020-05-27 03:15
Please use v3.17.3

**Comment by sopsick** [comment] 2020-05-27 12:37
I'm seeing the same issue. It appears to come from cases where the xml element has a trailing space (i.e., `<name >` vice `<name>`). 

I think the problem is with line 275 in xmlstr2xmlnode.js. It currently reads: 

`if(tagExp.lastIndexOf("/") === tagExp.length - 1){`. 

When there is an extra space tagExp.length equals zero and lastIndexOf returns -1 so you get -1 === -1. If the line is instead changed to 

`if(tagExp.length > 0 && tagExp.lastIndexOf("/") === tagExp.length - 1){`

 then the problem goes away.

**Comment by jdmairs** [comment] 2020-05-27 13:58
> Please use v3.17.3

It failed too.

**Comment by amitguptagwl** [comment] 2020-05-28 00:48
Thanks @sopsick to highlight the issue. I have fixed it in push to github.
@jdmairs try with the changes I pushed to github and let me know if that work.

**Comment by amitguptagwl** [comment] 2020-06-08 02:38
closing this issue. Please reopen if any concern is left to assist.

**Closed by amitguptagwl** 2020-06-08 02:38 UTC
Labels: Pending

**Comment by jdmairs** [comment] 2020-06-08 13:29
What version is this getting fixed in?

**Comment by amitguptagwl** [comment] 2020-06-08 23:53
Please check fast-xml-parser@3.17.4
