### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by lake2** [NaturalIntelligence/fast-xml-parser#171] opened 2019-07-20 15:53 UTC
### Checklist

* [ x] Have you asked your question on Stackoverflow or similar forum?
* [ x] Are you running the latest version?
* [ x] Have you included sample input, output, error, and expected output? 
* [ x] Have you checked if you are using correct configuration?
* [ x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

 
### Input

console logs error when transpile fast-xml-parser to es5
![image](https://user-images.githubusercontent.com/6293752/61580885-84c55d00-ab49-11e9-800e-33c85adae6d9.png)

### Code
```js
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const HtmlWebpackPlugin = require("html-webpack-plugin");
const webpack = require('webpack');
const package = require('./package.json');
const fecha = require('fecha');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');


module.exports = {
    mode: "production",
    devtool: 'source-map',
    entry: path.resolve(__dirname, "./src/ts/index.ts"),
    output: {
        filename: "app.[hash].js",
        path: path.resolve(__dirname, './pack/test/'),
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: "babel-loader",
                include: [/node_modules\\lit-html/, /node_modules\\fast-xml-parser/],
            },
            {
                test: /\.js$/,
                loader: "babel-loader",
                exclude: /node_modules/,
            },
            {
                test: /\.tsx?$/,
                loader: ["babel-loader", "ts-loader"],
            },
            {
                test: /\.less$/,
                loader: [MiniCssExtractPlugin.loader, 'css-loader?url=false', 'postcss-loader', 'less-loader'],
            },
            {
                test: /\.css$/,
                loader: [MiniCssExtractPlugin.loader, 'style-loader', 'css-loader?url=false', 'postcss-loader'],
            }
        ]
    },
    plugins: [
        new BundleAnalyzerPlugin({
            analyzerMode: "static",
            reportFilename: '../report.html',
            defaultSizes: "stat",
            generateStatsFile: true,
            statsFilename: '../report.json'
        }),
        new HtmlWebpackPlugin({ template: './src/index.html' }),
        new MiniCssExtractPlugin({
            filename: 'index.[hash].css',
        }),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify('production')
            },
            '_Version': JSON.stringify(package.version),
            '_RelaseTime': JSON.stringify(fecha.format(new Date(), 'YYYY/MM/DD')),
        }),
    ],
    resolve: {
        extensions: [".js", ".ts", ".tsx"],
    },
    optimization: {
        minimizer: [
            new UglifyJsPlugin({
                sourceMap: true,
                uglifyOptions: {
                    output: {
                        comments: false,
                    },
                },
            }),
        ],
        splitChunks: {
            // include all types of chunks
            chunks: 'all',
        }
    },
};

```

### expected data

**Would you like to work on this issue?**

- [ ] Yes
- [ x] No

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment] 2019-07-24 10:19
Its not much clear from the logs given where and what the issue is. Can you please try the already generated lib for browser and let me know if it is not es5 compatible.

**Comment by amitguptagwl** [comment] 2019-09-02 15:52
closing as no update. feel free to reopen if you think the problem is not solved.

**Closed by amitguptagwl** 2019-09-02 15:52 UTC
