### ISSUE TITLE
Why carriage return removed from values?

### ISSUE THREAD

**Issue by Delagen** [NaturalIntelligence/fast-xml-parser#45] opened 2018-02-08 11:21 UTC
### Checklist

* [x] Are you running the latest version?
* [x] Include sample input XML 
* [x] Include actual output
* [x] Include expected output
* [x] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?
* [x] Did you [star](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) the repository for further updates? ;)

I think
```
xmlData = xmlData.replace(/\r?\n/g, " ");//make it single line
```
should be removed
but
```
function buildAttributesMap(attrStr,options){
    attrStr = attrStr.replace(/\r?\n/g, " ");
```

But with this does not removed comments
```
xmlData = xmlData.replace(/<!--[\s\S]*?-->/g, "");//Remove  comments
```
resolves this

**Comment by amitguptagwl** [comment] 2018-02-09 03:15
@Delagen Have you found any test failing because of this change? (leaving the options naming aside)

If you check line number 51 of [parser.js](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/parser.js), It should be removing "carriage return" already.

**Comment by amitguptagwl** [comment] 2018-02-09 03:21
Sorry I missed your comment above. Why should it be removed?
```js
xmlData` = xmlData.replace(/\r?\n/g, " ");//make it single line
```

**Comment by Delagen** [comment] 2018-02-09 05:43
@amitguptagwl Check my PR it included test.
With this line you totally remove all CRLF from entire document.
So generic test will fail

```xml
<element><a>a
b
c</a><b>
a</b></element>
```
result with trim
```
{
"element": {
  "a": "a b c",
  "b": "a"
}
}
```

but should be
```
{
"element": {
  "a": "a\nb\nc",
  "b": "a"
}
}

```
or \r\n as in source XML

**Comment by amitguptagwl** [comment] 2018-02-09 06:54
In my opinion, both are correct until we have to convert json back to the XML. But I agree to replace CRLF in only the attribute's value with single space will keep it consistent for future changes. 

However if we go with current PR, it'll break the expected (though rare) output when multiple CDATA are present in a tag. I have found the solution by changing current RE. But give me some more time if I can make it more simple.

**Comment by amitguptagwl** [comment] 2018-02-09 07:27
ah!! it was simple only. I was doing mistake in `\s` and `\\s`

**Comment by amitguptagwl** [comment] 2018-02-09 07:56
I'll publish the changes soon after fixing online demo

**Comment by Delagen** [comment] 2018-02-09 08:10
When i make PR, all tests works.

**Comment by amitguptagwl** [comment] 2018-02-09 08:22
Yes, because I have added that test now. I was having a doubt that this change may break a scenario hence I have added now. 

I'm not sure if I can do the changes in in PR so I have committed the change on master branch. You can check the latest commit.

Code wise it is same as your PR + one small change. Test wise I have added 1 small test and fixed validator for the same.

Thanks a lot for your kind suggestion.

**Comment by amitguptagwl** [comment] 2018-02-09 08:31
@Delagen changes are published. Many thanks for your effort and time.

**Closed by amitguptagwl** 2018-02-09 08:31 UTC

**Comment by Delagen** [comment] 2018-02-09 08:33
Thanks

**Comment by Delagen** [comment] 2018-02-09 08:42
```xml
<el><![CDATA[<a>&lt;<a/>&lt;b&gt;2</b>]]]]>
<![CDATA[]]]]><![CDATA[>&amp;]]>a</el>
```
seems to be
```json
{
"el":"<a>&lt;<a/>&lt;b&gt;2</b>]]\r\n]]>&amp;a"
}
```

**Comment by amitguptagwl** [comment] 2018-02-09 08:49
No it should't replace CRLF in CDATA. check the last test of `cdata_spec.js`

```js
 it("should validate XML with repeated multiline CDATA and comments", function () {
        var fs = require("fs");
        var path = require("path");
        var fileNamePath = path.join(__dirname, "assets/mixed.xml");
        var xmlData = fs.readFileSync(fileNamePath).toString();


        var expected = {
            "ns:root": {
                "ptag": [
                    {
                        "nestedtag": "nesteddata",
                        "@_attr": "val",
                        "@_boolean": true,
                        "#text": "some dataafter"
                    },
                    "before text\n        <nestedtag>\n            nested cdata 1\n        </nestedtag>\n    middle\n        <nestedtag>\n            nested cdata 2\n        </nestedtag>\n    after\n        <nestedtag>\n            nested cdata 3\n        </nestedtag>\n    end"
                ],
                "@_xmlns:soap": "http://schemas.xmlsoap.org/soap/envelope/"
            }
        };

            var result = parser.parse(xmlData,{
                ignoreAttributes:false,
                allowBooleanAttributes:true
            });
        //console.log(JSON.stringify(result,null,4));
        expect(result).toEqual(expected);
    });
```

Is it not expected behavior?

**Comment by Delagen** [comment] 2018-02-09 09:04
Not in, BETWEEN Cdata blocks, see example

**Comment by amitguptagwl** [comment] 2018-02-09 09:34
Sorry for my eye number but I couldn't spot what you said. In above example "\n    middle\n" is something in between the CDATA. Can you please tell me where exactly?

**Comment by Delagen** [comment] 2018-02-09 09:49
For example:
```
<element>
<![CDATA[abc]]>
<![CDATA[def]]>
<![CDATA[ghi]]>
</element>
```
should evaluate to
```
"element":"abcdefghi"
```
or
```
"element":"abc\ndef\nghi"
```
???
I think to second
or even
```
"element":"\nabc\ndef\nghi\n"
```
if trimValues:false

**Comment by amitguptagwl** [comment] 2018-02-09 10:10
Hmm, now I see. I even seen in some converter online that they place `\n` before CDATA even if they appear in single line.
I'm not sure what should happen as there is no standard but we should do what majority of converters do.
E.g. if we take CDATA as nested tag which passes it's value to parent tag as raw text then, we should not add `\n`. But if we take it just as a placeholder then yes we should.
